{{- if and (not .Values.apiKey.existingSecret) .Values.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.apiKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "agent.labels" . | nindent 4 }}
stringData:
  {{ .Values.apiKey.secretKey }}: {{ .Values.apiKey.value | quote }}
{{- end }}
