services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      # set the target to prod and rebuild to use production settings
      target: dev
    ports:
      - "8081:3000"
      - "4000:4000"
      - "24678:24678"
    environment:
      - NUXT_PUBLIC_APP_VERSION=v9.9.9
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
      - NUXT_PUBLIC_WS_URL=ws://localhost:4000
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
      - NUXT_CONTENT_WS_URL=ws://localhost:4000/ws
    volumes:
      - ./frontend:/src
      - node_modules:/src/node_modules
    networks:
      - main

  postgres:
    container_name: postgres
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - main

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.3
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - "postgres"
    restart: unless-stopped
    networks:
      - main

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - main

  backend: &backend
    container_name: backend
    build:
      context: ./backend
      target: local
    command:
      - "python3"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CELERY_TASK_ALWAYS_EAGER=${CELERY_TASK_ALWAYS_EAGER:-0}
      - DJANGO_EMAIL_HOST=mailhog
      - DEBUG=1
      - POSTGRES_SERVICE_HOST=postgres
      - REDIS_SERVICE_HOST=redis
      - DJANGO_SETTINGS_MODULE=backend.settings.development
      - OPENAI_API_KEY=${OPENAI_API_KEY:-.}
      - NVIDIA_API_KEY=${NVIDIA_API_KEY:-.}

      # celery beat
      - PIDFILE=
      - TZ=America/New_York
    depends_on:
      - postgres
      - redis

  celery_worker:
    <<: *backend
    container_name: celery_worker
    command:
      - "python3"
      - "manage.py"
      - "start_celery_worker"
    ports: []
    healthcheck:
      test: ["CMD", "celery", "--app=backend.celery_app:app", "inspect", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_beat:
    <<: *backend
    container_name: celery_beat
    command:
      - python3
      - manage.py
      - start_celery_beat
    ports: []

  # migrate command
  migrate:
    <<: *backend
    container_name: migrate
    command:
      - python3
      - manage.py
      - migrate
    ports: []
    depends_on:
      - postgres
      - redis
      - backend
    restart: "on-failure"

  # migrate command
  makemigrations:
    <<: *backend
    container_name: makemigrations
    command:
      - python3
      - manage.py
      - makemigrations
    ports: []
    depends_on:
      - postgres
      - redis
      - backend
    restart: "on-failure"

  generate-schema:
    <<: *backend
    container_name: schema
    command:
      - python3
      - manage.py
      - spectacular
      - --color
      - --file
      - static/openapi/schema.yml
    ports: []
    depends_on:
      - postgres
      - redis
      - backend
    restart: "on-failure"

  flower:
    container_name: flower
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      celery_worker:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - TZ=America/New_York
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  pg-data:
  redis-data:
  pgadmin:
  node_modules:
