# Generated by Django 5.2 on 2025-05-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="generated_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="generated_images/"
            ),
        ),
        migrations.AlterField(
            model_name="inferencerequest",
            name="inference_type",
            field=models.CharField(
                choices=[
                    ("llm_chat", "LLM Chat"),
                    ("llm_completion", "LLM Completion"),
                    ("image_generation", "Image Generation"),
                ],
                max_length=20,
            ),
        ),
    ]
