# Generated by Django 5.2 on 2025-05-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0002_inferencerequest_generated_image_and_more"),
        ("services", "0003_imagegenmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="image_gen_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inference_requests",
                to="services.imagegenmodel",
            ),
        ),
    ]
