# Generated by Django 5.2 on 2025-05-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0003_inferencerequest_image_gen_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="input_image",
            field=models.TextField(
                blank=True,
                help_text="Optional input image (data URL) for canny/depth modes.",
                null=True,
            ),
        ),
    ]
