# Generated by Django 5.2 on 2025-05-30 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0004_inferencerequest_input_image"),
        ("services", "0004_ttsservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="speech_input",
            field=models.FileField(blank=True, null=True, upload_to="tts_inputs/"),
        ),
        migrations.AddField(
            model_name="inferencerequest",
            name="speech_output",
            field=models.FileField(blank=True, null=True, upload_to="tts_outputs/"),
        ),
        migrations.AddField(
            model_name="inferencerequest",
            name="tts_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inference_requests",
                to="services.ttsservice",
            ),
        ),
    ]
