# Generated by Django 5.2 on 2025-06-01 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0005_inferencerequest_speech_input_and_more"),
        ("services", "0004_ttsservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="llm_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inference_requests",
                to="services.llmmodel",
            ),
        ),
    ]
