# Generated by Django 5.2 on 2025-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0007_inferencerequest_video_gen_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="input_image_file",
            field=models.ImageField(
                blank=True,
                help_text="Optional uploaded input image file.",
                null=True,
                upload_to="input_images/",
            ),
        ),
        migrations.AlterField(
            model_name="inferencerequest",
            name="inference_type",
            field=models.CharField(
                choices=[
                    ("llm_chat", "LLM Chat"),
                    ("llm_completion", "LLM Completion"),
                    ("image_generation", "Image Generation"),
                    ("video_generation", "Video Generation"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inferencerequest",
            name="input_image",
            field=models.TextField(
                blank=True,
                help_text="Optional input image data URL for reference.",
                null=True,
            ),
        ),
    ]
