# Generated by Django 5.2 on 2025-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0008_inferencerequest_input_image_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerequest",
            name="generated_video",
            field=models.FileField(
                blank=True,
                help_text="Generated video file from video generation requests",
                null=True,
                upload_to="generated_videos/",
            ),
        ),
    ]
