# Generated by Django 5.2 on 2025-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="slug",
            field=models.SlugField(
                default=1,
                help_text="URL-friendly version of the name",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="name",
            field=models.CharField(
                help_text="Name of the LLM model (e.g. qwen3-8b)",
                max_length=255,
                unique=True,
            ),
        ),
    ]
