# Generated by Django 5.2 on 2025-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_llmmodel_slug_alter_llmmodel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the image generation service",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the service",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="Base URL for the image generation API"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("FLUX_NIM", "Flux Nim"),
                            ("INVOKEAI", "InvokeAI"),
                            ("COMFYUI", "ComfyUI"),
                        ],
                        help_text="Type of image generation service",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Image Generation Model",
                "verbose_name_plural": "Image Generation Models",
                "ordering": ["-created_at"],
            },
        ),
    ]
