# Generated by Django 5.2 on 2025-05-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_imagegenmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TTSService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("url", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[("Dia", "Dia"), ("ChatTTS", "ChatTTS")], max_length=16
                    ),
                ),
            ],
        ),
    ]
