# Generated by Django 5.2 on 2025-06-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_ttsservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoGenService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("slug", models.SlugField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("HUNYUAN_VIDEO", "Hunyuan Video")], max_length=20
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Generation Service",
                "verbose_name_plural": "Video Generation Services",
            },
        ),
    ]
